# Generated by Django 3.0.1 on 2019-12-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20191229_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='information',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='origin',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
