# Generated by Django 3.0.1 on 2019-12-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20191229_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video',
            field=models.CharField(max_length=255),
        ),
    ]
